<a href="https://colab.research.google.com/github/torrhen/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
# summary of available GPU
!nvidia-smi

1.12.1+cu113
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
# torch.tensor for tensor attributes and functions
# scalars
# scalars and tensors variables with rank less than 2 are lower case stylistically
x = torch.tensor(10)
print(x)
y = torch.tensor(20)
print(y)
z = torch.tensor(5)
print(z)
# return value of tensor scalar as python integer
print(x.item()) # can only be used for rank 0 tensors (scalars)
print(y.item())
print(z.item())

tensor(10)
tensor(20)
tensor(5)
10
20
5


In [ ]:
# vector
x_vec = torch.tensor([10, 20]) # remember the []'s
print(x)
print(x_vec)
# ndim returns the number of dimensins (rank) of a tensor
print("rank of x:\t", x.ndim) # ndim is alias for dim() method
print("rank of x_vec:\t", x_vec.ndim)
# NUMBER OF NESTED BRACKETS []'s

print("shape of x_vec\t", x_vec.shape) # number of elements along each dimension

tensor(10)
tensor([10, 20])
rank of x:	 0
rank of x_vec:	 1
shape of x_vec	 torch.Size([2])


In [ ]:
# matrix
# matrices and tensor variables with a rank greater than 1 are upper case stylistically
X_MAT = torch.tensor([[2, 4],
                      [6, 8],
                      [10, 12]]) # rank 2 (ndim = 2)
print(X_MAT)
print("x_mat shape:\t", X_MAT.shape) 

tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])
x_mat shape:	 torch.Size([3, 2])


In [ ]:
# tensor
X_TEN = torch.tensor([[[1, 2, 3, 4],
                       [5, 6, 7, 8]], 
                      [[8, 7, 6, 5],
                       [4, 3, 2, 1]]])
print("x_ten rank:\t", X_TEN.ndim) # 3
print("x_ten shape:\t", X_TEN.shape) # [2, 2, 4]

# errors can occur when operating on two or more tensors with incompatible shapes

x_ten rank:	 3
x_ten shape:	 torch.Size([2, 2, 4])


In [ ]:
# create a random tensor
r = torch.rand(5, 5) # uniform distribution [0, 1)
# r = torch.rand(size=(5, 5)) is the same tensor
print(r)

tensor([[0.6309, 0.5231, 0.2305, 0.2840, 0.1543],
        [0.2422, 0.5006, 0.6026, 0.1476, 0.2363],
        [0.6203, 0.5524, 0.7048, 0.5440, 0.4113],
        [0.0422, 0.1145, 0.0020, 0.3196, 0.3239],
        [0.1509, 0.0417, 0.6831, 0.0499, 0.2133]])


In [ ]:
# create a zeros tensor
z = torch.zeros(size=(2, 3))
print(z)
# create a ones tensor
o = torch.ones(size=(4, 5))
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
# create a tensor from range or sequence of values
a = torch.range(0, 5) # deprecated 0, 1, 2, 3, 4, 5 [start, end](inconsistent with python ranges)
print(a)
b = torch.arange(1, 11) # use this instead, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 [start, end)
print(b)

tensor([0., 1., 2., 3., 4., 5.])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


In [ ]:
# create a tensor using the shape of another tensor
# create a tensor of zeros with the same shape as b (above)
z_like = torch.zeros_like(b)
print(z_like)
# create a tensor of ones with the same shape as b (above)
o_like = torch.ones_like(b)
print(o_like)
# create an empty tensor with the same shape as b (above)
e_like = torch.empty_like(b)
print(e_like) # uninitialized, undefined values
# create a tensor full of a specific value with the same shape as b (above)
f_like = torch.full_like(b, 5)
print(f_like)


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([98189056,        0,        0,        0,        0,        0,        0,
               0,        0,        0])
tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


In [ ]:
# tensor data type
# default data type for all float tensors in PyTorch is float32, regardless if None is specified
x_float32 = torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=None)
print(x_float32.dtype) # float32 single precision

x_float16 = torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.float16)
print(x_float16.dtype) # float16 half precision

# it is faster to calculate operations on numerical values with smaller precision

# errors MAY occur when operating on two or more tensors with different precisions

torch.float32
torch.float16


In [ ]:
# tensor devices
x_cpu = torch.tensor([1, 2, 3]) # device is 'cpu' by default
#x_gpu = torch.tensor([1, 2, 3], device='cuda') # hardware option must be selected

print(x_cpu.device) # cpu
#print(x_gpu.device) # cuda:0

# errors occur when operating on two or more tensors stored on different devices

cpu


In [ ]:
# tensor addition
a = torch.tensor([4, 8, 6], dtype=torch.float32)
b = torch.tensor([5, 7, 9], dtype=torch.float32)
# b = torch.tensor([3]) # broadcasted to meet shape requirements of a
print(a + 10)
print(a + b)
print(a.add(b))
# print(a.add_(b)) # inplace

tensor([14., 18., 16.])
tensor([ 9., 15., 15.])
tensor([ 9., 15., 15.])


In [ ]:
# tensor subtraction
print(a - 10)
print(a - b)
print(a.sub(b))
# print(a.sub_(b)) # inplace

tensor([-6., -2., -4.])
tensor([-1.,  1., -3.])
tensor([-1.,  1., -3.])


In [ ]:
# tensor (element-wise) multiplication
print(a * 4)
print(a * b)
print(a.mul(b))
# print(a.mul_(b)) # inplace

tensor([16., 32., 24.])
tensor([20., 56., 54.])
tensor([20., 56., 54.])


In [ ]:
# tensor division
print(a / 2)
print(b / a)
print(b.div(a))
# print(b.div_(a)) # inplace

tensor([2., 4., 3.])
tensor([1.2500, 0.8750, 1.5000])
tensor([1.2500, 0.8750, 1.5000])


In [ ]:
# matrix multiplication (dot product)
print(a @ b)
print(a.matmul(b))

tensor(130.)
tensor(130.)


In [ ]:
# matrix transpose
# useful when inner dimensions for matrix multiplication do not match
x = torch.rand(3, 4)
print(x) # (3, 4)
print(x.t()) # (4, 3)
# print(x.t_()) # inplace 

tensor([[0.7776, 0.7692, 0.6552, 0.3097],
        [0.6931, 0.3628, 0.2188, 0.7973],
        [0.8401, 0.0103, 0.8888, 0.4690]])
tensor([[0.7776, 0.6931, 0.8401],
        [0.7692, 0.3628, 0.0103],
        [0.6552, 0.2188, 0.8888],
        [0.3097, 0.7973, 0.4690]])


In [ ]:
# tensor aggregation
x = torch.arange(20)
print(x)
# return min element
print(torch.min(x)) # 0
print(x.min())
# return max element
print(torch.max(x)) # 19
print(x.max())
# return average of elements in the tensor
print(torch.mean(x.type(torch.float32))) # torch.mean requires float input
print(x.type(torch.float32).mean())
# return the sum of elements in the tensor
print(torch.sum(x))
print(x.sum())
# return the index of the max element in the tensor
print(torch.argmax(x))
print(x.argmax())
# return the index of the min element in the tensor
print(torch.argmin(x))
print(x.argmin())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor(0)
tensor(0)
tensor(19)
tensor(19)
tensor(9.5000)
tensor(9.5000)
tensor(190)
tensor(190)
tensor(19)
tensor(19)
tensor(0)
tensor(0)


In [ ]:
# all below are used to fix issues with the shape or dimensionality of tensors we want to work with

# reshaping tensors
x = torch.arange(1., 13.)
print(x)
# new shapes must be compatible with total number of elements in the tensor
print(x.reshape(3, 4))
print(x.reshape(6, 2))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [ ]:
# changing tensor view
# similar to reshape except that new tensors shares the memory of the original tensor
# changing output therefore changes the original input

a = torch.arange(1, 21)
print(a)
b = a.view(10, 2)
print(b)
b[0] = b[0] * 0
print(a) # first 2 elements of a have been set to zero even though b was operated on


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
tensor([ 0,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])


In [ ]:
# stacking tensors
x = torch.tensor([1, 2, 3, 4])
print(x.ndim)
print(x.shape) # [4]
# when dim = 0, stacking changes the first dimension of new tensor
y = torch.stack([x, x, x], dim=0) # new shape is [3, 4]
print(y)
print(y.ndim)
print(y.shape)
# when dim = r-1, stacking changes the r-1 dimension of the new tensor where r is the rank of the output tensor
z = torch.stack([x, x, x], dim=1) # new shape is [4, 3]
print(z)
print(z.ndim)
print(z.shape)

# vertical stacking
v = torch.vstack([x, x, x])
print(v) # new shape [2, 4]
print(v.shape)

# horizontal stacking
h = torch.hstack([x, x, x])
print(h) # new shape [8]
print(h.shape)

1
torch.Size([4])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
2
torch.Size([3, 4])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
2
torch.Size([4, 3])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
torch.Size([3, 4])
tensor([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])
torch.Size([12])


In [ ]:
# squeeze tensor shape
# returns a tensor with all dimensions of size 1 removed
# shares the same memory as the original tensor (like torch.view)
r = torch.rand(2, 1, 4)
print(r)
print(r.shape)
r_s = torch.squeeze(r)
print(r_s)
print(r_s.shape)

# torch.squeeze(input, dim) can be used to squeeze tensor for a specific dim and ignore all other 1 dimensions

tensor([[[0.1865, 0.9208, 0.4622, 0.2939]],

        [[0.7210, 0.7501, 0.5583, 0.9750]]])
torch.Size([2, 1, 4])
tensor([[0.1865, 0.9208, 0.4622, 0.2939],
        [0.7210, 0.7501, 0.5583, 0.9750]])
torch.Size([2, 4])


In [ ]:
# unsqueeze tensor shape
# returns a new tensor with a dimension of 1 added for a specific dimension
# shares the same memory as the original tensor (like torch.view)
r = torch.rand(10)
print(r)
print(r.shape) # [10]
r_us = torch.unsqueeze(r, dim=0)
print(r_us)
print(r_us.shape) # [1, 10]

tensor([0.9643, 0.1158, 0.8914, 0.4416, 0.4072, 0.8891, 0.2467, 0.0380, 0.3243,
        0.9806])
torch.Size([10])
tensor([[0.9643, 0.1158, 0.8914, 0.4416, 0.4072, 0.8891, 0.2467, 0.0380, 0.3243,
         0.9806]])
torch.Size([1, 10])


In [ ]:
# permute tensor dimensions
# changes the shape of a tensor by reordering the lsit of dimensions
# returns a view - shares the memory of original input tensor - same data
x = torch.rand(1, 2, 3)
print(x)
print(x.shape)
# create a new order for the dimensions of x
y = torch.permute(x, [2, 1, 0]) # new shape for x of [3, 2, 1]
print(y)
print(y.shape)

tensor([[[0.9760, 0.9335, 0.3542],
         [0.8364, 0.7478, 0.0047]]])
torch.Size([1, 2, 3])
tensor([[[0.9760],
         [0.8364]],

        [[0.9335],
         [0.7478]],

        [[0.3542],
         [0.0047]]])
torch.Size([3, 2, 1])


In [ ]:
import torch
# indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(x[0][2][2]) # 9
print(x[:, :, 2]) # [3, 6, 9]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(9)
tensor([[3, 6, 9]])


In [ ]:
import numpy as np

# convert numpy array to tensor
x = np.arange(1.0, 10.0) # default float type is float64
print(x)
y = torch.from_numpy(x) # tensor becomes float64, new tensor in memory
print(y)

# convert tensor to numpy array
z = torch.ones(10) # default float type is float 32
print(z)
a = z.numpy() # numpy array becomes float32, new array in memory
print(a)

# beware the default type for numpy arrays and tensors, converting between each reflects the default type of the original structure


[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [ ]:
# reproducibility - removing randomness
# ensure easier testing and experimentation of neural networks by controlling the value of parameters during each iteration
# e.g. every random initilaization of a parameter will be different between runs
import torch

torch.manual_seed(10) # set then manual seed before each block of (random) code to get a deterministic result
A = torch.rand(3, 3)
torch.manual_seed(10) # identical seeds
B = torch.rand(3, 3)
print(A)
print(B)
print(A == B)


tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])
tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [ ]:
# GPU agnostic code
# run the code regardless of which device is available
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu' # set the device to allocate pytorch objects on
if device == 'cuda':
  print(torch.cuda.device_count()) # how many GPUs are connected
  !nvidia-smi # print information about the GPU available


1
Fri Nov  4 11:18:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    30W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----

In [ ]:
# allocating models and tensors onto a GPU leads to faster computations

# move tensor to gpu with the to() method (if available)
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = x.to(device)
print(y)

# numpy cannot be used with objects allocated on GPUs
# objects must be re-allocated to the CPU first before numpy operations using .cpu() method
z = y.cpu().numpy()
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0')
[[1 2]
 [3 4]
 [5 6]]
